#: include includes/colors.kv
#: include page/sale.kv
#: import C kivy.utils.get_color_from_hex

<Dashboard@BoxLayout>:

<SideButton@Button>:
    markup: True
    background_color: C(sidebar_color)
    background_normal: ''

<Sep@Label>:
    size_hint_y: None
    height: '3px'

<Dashboard>:
    BoxLayout:
        size_hint_x: None
        orientation: 'vertical'
        width: '100px'
        SideButton:
            id: dashboardButton
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[color={}][b][size={}][font=PICTO]7[/font][/b][/size][/color]'.format(sidebar_color,int(self.width/2))
                Label:
                    markup: True
                    text: '[color={}][size={}][b]Dashboard[/b][/size][/color]'.format(sidebar_color, int(self.width/6))

        Sep:
        SideButton:
            on_press:
                root.parent.parent.transition.direction="left"
                root.parent.parent.current = 'sales'
            BoxLayout:

                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=PICTO]6[/font][/size]'.format(int(self.width/2))
                Label:
                    markup: True
                    text: '[size={}]Sales[/size]'.format(int(self.width/6))
        Sep
        SideButton:
            on_press:
                root.parent.parent.transition.direction="left"
                root.parent.parent.current = 'inventory'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=PICTO]\[/font][/size]'.format(int(self.width/2))
                Label:
                    markup: True
                    text: '[size={}]Inventory[/size]'.format(int(self.width/6))
        Sep
        SideButton:
            on_press:
                root.parent.parent.transition.direction="left"
                root.parent.parent.current = 'settings'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=rap]Ñ[/font][/size]'.format(int(self.width/2))
                Label:
                    markup: True
                    text: '[size={}]Settings[/size]'.format(int(self.width/6))

    BoxLayout: