<ExportsTable1Header@GridLayout>:
    cols: 9
    size_hint_y: None
    height: '90px'
    canvas.before:
        Color:
            rgba: C('#455a64')
        Rectangle:
            pos: self.pos
            size: self.size
    Head:
        text: "[size=20][b]id[/b][/size]"
    Head:
        text: "[size=20][b]Destination[/b][/size]"
    Head:
        text: "[size=20][b]Date[/b][/size]"
    Head:
        text: "[size=20][b]Status[/b][/size]"
    Head:
        text: "[size=20][b]Options[/b][/size]"

<ExportsTable2Header@GridLayout>:
    cols: 9
    size_hint_y: None
    height: '90px'
    canvas.before:
        Color:
            rgba: C('#455a64')
        Rectangle:
            pos: self.pos
            size: self.size
    Head:
        text: "[size=20][b]id[/b][/size]"
    Head:
        text: "[size=20][b]Export ID[/b][/size]"
    Head:
        text: "[size=20][b]Product ID[/b][/size]"
    Head:
        text: "[size=20][b]Quantity[/b][/size]"
    Head:
        text: "[size=20][b]Unit Price[/b][/size]"
    Head:
        text: "[size=20][b]Options[/b][/size]"