#: include includes/colors.kv
#: import C kivy.utils.get_color_from_hex

#:import MDTextField kivymd.textfields.MDTextField
#:import MDLabel kivymd.label.MDLabel
#:import MDIconButton kivymd.button.MDIconButton


<SideButton@Button>:
    markup: True
    background_color: C(sidebar_color)
    background_normal: ''

<Sep@Label>:
    size_hint_y: None
    height: '3px'

<Sales>:
    BoxLayout:
        size_hint_x: None
        orientation: 'vertical'
        width: '250px'
        SideButton:
            on_press:
                root.parent.parent.transition.direction="right"
                root.parent.parent.current = 'dashboard'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=PICTO]7[/font][/size]'.format(int(self.width/5))
                Label:
                    markup: True
                    text: '[size={}]Dashboard[/size]'.format(int(self.width/8))

        Sep:
        SideButton:
            id: saleButton
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[color={}][b][size={}][font=PICTO]6[/font][/size][/b][/color]'.format(sidebar_color,int(self.width/5))
                Label:
                    markup: True
                    text: '[color={}][b][size={}]Sales[/size][/b][/color]'.format(sidebar_color,int(self.width/8))
        Sep
        SideButton:
            on_press:
                root.parent.parent.transition.direction="left"
                root.parent.parent.current = 'inventory'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=PICTO]\[/font][/size]'.format(int(self.width/5))
                Label:
                    markup: True
                    text: '[size={}]Inventory[/size]'.format(int(self.width/8))
        Sep
        SideButton:
            on_press:
                root.parent.parent.transition.direction="left"
                root.parent.parent.current = 'settings'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=rap]Ñ[/font][/size]'.format(int(self.width/5))
                Label:
                    markup: True
                    text: '[size={}]Settings[/size]'.format(int(self.width/8))

    BoxLayout:
        orientation: 'vertical'
        spacing: '3px'
        padding: '3px'
        BoxLayout:
            GridLayout:
                cols: 1
                size_hint_x: None
                width: '300px'
                spacing: '10px'
                padding: '10px'
                MDTextField:
                    hint_text: 'ID'
                BoxLayout:
                    size_hint_y: None
                    height: '40px'
                    MDIconButton:
                        icon: 'calendar'
                        on_release: root.sale_date_pick()
                    MDTextField:
                        id: sale_date_picker_label
                        hint_text: 'Date'
                        disabled: True

                MDTextField:
                    hint_text: 'Status'
            Button:
                background_color: C(color_primary)
				text: 'Table'
        BoxLayout:
            GridLayout:
                cols: 1
                size_hint_x: None
                width: '300px'
                spacing: '10px'
                padding: '10px'
                MDTextField:
                    hint_text: 'Product'
                MDTextField:
                    hint_text: 'Quantity'
                BoxLayout:
                    spacing: '3px'
                    Button:
                        size_hint_y: None
                        height: '60px'
                        text: 'sell'
                        background_normal: ''
                        background_color: C(color_primary)
                    Button:
                        size_hint_y: None
                        height: '60px'
                        text: 'delete'
                        background_normal: ''
                        background_color: C(danger)
            Button:
                text: 'Table'
				background_color: C(color_primary)