#: include includes/colors.kv
#: import C kivy.utils.get_color_from_hex

#:import MDTextField kivymd.textfields.MDTextField
#:import MDLabel kivymd.label.MDLabel
#:import MDIconButton kivymd.button.MDIconButton
#:import date datetime.date

<SideButton@Button>:
    markup: True
    background_color: C(sidebar_color)
    background_normal: ''

<Sep@Label>:
    size_hint_y: None
    height: '3px'


<Sales>:
    BoxLayout:
        size_hint_x: None
        orientation: 'vertical'
        width: '100px'
        SideButton:
            on_press:
                root.parent.parent.transition.direction="right"
                root.parent.parent.current = 'dashboard'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=PICTO]7[/font][/size]'.format(int(self.width/2))
                Label:
                    markup: True
                    text: '[size={}]Dashboard[/size]'.format(int(self.width/6))

        Sep:
        SideButton:
            id: saleButton
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[color={}][b][size={}][font=PICTO]6[/font][/size][/b][/color]'.format(sidebar_color,int(self.width/2))
                Label:
                    markup: True
                    text: '[color={}][b][size={}]Sales[/size][/b][/color]'.format(sidebar_color,int(self.width/6))
        Sep
        SideButton:
            on_press:
                root.parent.parent.transition.direction="left"
                root.parent.parent.current = 'inventory'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=PICTO]\[/font][/size]'.format(int(self.width/2))
                Label:
                    markup: True
                    text: '[size={}]Inventory[/size]'.format(int(self.width/6))
        Sep
        SideButton:
            on_press:
                root.parent.parent.transition.direction="left"
                root.parent.parent.current = 'settings'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=rap]Ñ[/font][/size]'.format(int(self.width/2))
                Label:
                    markup: True
                    text: '[size={}]Settings[/size]'.format(int(self.width/6))

    BoxLayout:
        orientation: 'vertical'
        spacing: '3px'
        padding: '3px'
        BoxLayout:
            GridLayout:
                cols: 1
                size_hint_x: None
                width: '300px'
                spacing: '10px'
                padding: '10px'
                BoxLayout:
                    size_hint_y: None
                    height: '50px'
                    #MDIconButton:
                    #    icon: 'calendar'
                    #    on_release: root.sale_date_pick()

                    MDTextField:
                        id: sale_date_picker_label
                        hint_text: 'Date'
                        text: str(date.today())
                        disabled: True
                MDTextField:
                    id: sales_submitted_by
                    hint_text: 'Submitted By'
                    text: "Hema"
                    disabled: True
                #MDTextField:
                #    id: sales_status
                #    hint_text: 'Status'
                MDFloatingActionButton:
                    id: float_act_btn
                    text_color: C('#FFFFFF')
                    icon: 'plus'
                    # opposite_colors: True
                    md_bg_color: C(color_primary)
                    elevation_normal: 8
                    pos_hint: {'center_x': 0.5, 'center_y': 0.2}

            Button:
                background_color: C(color_primary)
				text: 'Table'
        BoxLayout:
            GridLayout:
                cols: 1
                size_hint_x: None
                width: '300px'
                spacing: '10px'
                padding: '10px'
                MDTextField:
                    id: sales_barcode
                    hint_text: 'Barcode'
                MDTextField:
                    id: sales_voucher_product_id
                    hint_text: 'Product'
                    disables: True
                MDTextField:
                    id: sales_voucher_product_quantity
                    hint_text: 'Quantity'
                GridLayout:
                    cols: 2
                    spacing: '30px'
                    MDFloatingActionButton:
                        id: float_act_btn
                        text_color: C('#FFFFFF')
                        icon: 'cash-multiple'
                        # opposite_colors: True
                        md_bg_color: C(green_color)
                        elevation_normal: 8
                        pos_hint: {'center_x': 0.5, 'center_y': 0.2}
                    MDFloatingActionButton:
                        id: float_act_btn
                        text_color: C('#FFFFFF')
                        icon: 'delete-forever' # 'close'
                        # opposite_colors: True
                        md_bg_color: C(danger)
                        elevation_normal: 8
                        pos_hint: {'center_x': 0.5, 'center_y': 0.2}
            Button:
                text: 'Table'
				background_color: C(color_primary)