#: include includes/colors.kv
#: import C kivy.utils.get_color_from_hex

<Setting@BoxLayout>:

<SideButton@Button>:
    markup: True
    background_color: C(sidebar_color)
    background_normal: ''

<Sep@Label>:
    size_hint_y: None
    height: '3px'

<Setting>:
    BoxLayout:
        size_hint_x: None
        orientation: 'vertical'
        width: '100px'
        SideButton:
            on_press:
                root.parent.parent.transition.direction="right"
                root.parent.parent.current = 'dashboard'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=PICTO]7[/font][/size]'.format(int(self.width/2))
                Label:
                    markup: True
                    text: '[size={}]Dashboard[/size]'.format(int(self.width/6))

        Sep:
        SideButton:
            on_press:
                root.parent.parent.transition.direction="right"
                root.parent.parent.current = 'sales'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=PICTO]6[/font][/size]'.format(int(self.width/2))
                Label:
                    markup: True
                    text: '[size={}]Sales[/size]'.format(int(self.width/6))
        Sep
        SideButton:
            on_press:
                root.parent.parent.transition.direction="right"
                root.parent.parent.current = 'inventory'
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[size={}][font=PICTO]\[/font][/size]'.format(int(self.width/2))
                Label:
                    markup: True
                    text: '[size={}]Inventory[/size]'.format(int(self.width/6))
        Sep
        SideButton:
            id: settingButton
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                Label:
                    markup: True
                    text: '[color={}][b][size={}][font=rap]Ñ[/font][/size][/b][/color]'.format(sidebar_color,int(self.width/2))
                Label:
                    markup: True
                    text: '[color={}][b][size={}]Settings[/size][/b][/color]'.format(sidebar_color,int(self.width/6))

    BoxLayout: